config/routes.rb
Rails.application.routes.draw do
  root "contacts#index"
  resources :contacts
  get "/contact/detail/:id", to: "contacts#show"



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :name,presence: true
    validates :phone_number,presence: true
    validates :email,presence: true

end

app/models/group.rb
class Group < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
   @contacts = Contact.all
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      respond_to do |format|
        format.html { redirect_to root_path,notice:"Data Berhasil ditambahkan !" }
      end
    else
      return 'gagal'; 
    end
  end
  def edit
    @contact = Contact.find(params[:id]) 
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update(contact_params)
      respond_to do |format|
        format.html { redirect_to root_path,notice: "Data berhasil diupdate" }
      end
    end 
  end

  def destroy
  @contact = Contact.find(params[:id]) 
    if @contact.destroy
      respond_to do |format|
        format.html { redirect_to root_path,notice:'Data Berhasil Dihapus' }
      end
    else 
      
    end  
  end

  private
    def contact_params #digunakan untuk mendefinisikan form yang dijinkan masuk kedalam database 
      params.require(:contact).permit(:name,:phone_number,:email);
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
    <div>
        <%=form.label :name,class:'form-label' %>
        <%=form.text_field :name,class:'form-control' %>
    </div>
    <div>
        <%=form.label :phone_number,class:'form-label' %>
        <%=form.text_field :phone_number,class:'form-control' %>
    </div>
    <div>
        <%=form.label :email,class:'form-label' %>
        <%=form.email_field :email,class:'form-control' %>
    </div>
    <div>
        <%=form.submit class:'btn btn-primary btn-sm mt-3' %>
    </div>
    <% end %>

app/views/contacts/edit.html.erb
<div class="container mt-3">
<h2 class="mb-3">Edit Tambah Kontak</h2>
    <%= render 'form', contact: @contact %>
</div>

app/views/contacts/index.html.erb
<div class="container mt-5">

<% if notice !=nil %>    
<div class="alert alert-danger" role="alert">
  <%= notice %>
</div>
<% end %>

    <table class="table table-hover">
      <tr>
          <th>No</th>
          <th>Name</th>
          <th>Nomor Telepon</th>
          <th>Email</th>
          <th>Aksi</th>
      </tr>
      <% index= 1 
      @contacts.each do |contact| %>    
      <tr>
      
          <td><%=index %></td>
          <td><%=contact.name %></td>
          <td><%=contact.phone_number %></td>
          <td><%=contact.email %></td>
          <td> <a href="/contacts/<%= contact.id%>/edit" class="btn btn-warning btn-sm mx-2">Edit</a> <a href="/contacts/<%= contact.id%>" class="btn btn-primary btn-sm mx-2">Detail</a> <%= button_to "Hapus Data", contact, method: :delete,class:'btn btn-danger btn-sm' %> </td>
      </tr>
      <% end %>
    </table>
</div>

app/views/contacts/new.html.erb
<div class="container mt-3">
<h2 class="mb-3">Form Tambah Kontak</h2>
    <%= render 'form', contact: @contact %>
</div>

app/views/contacts/show.html.erb
<div class="container mt-5">
    <div class="card" style="width:15rem">
        <div class="card-body">
            <ul>
                <li><%=@contact.name%></li>
                <li><%=@contact.email%></li>
                <li><%=@contact.phone_number%></li>
            </ul>
             <%= button_to "Hapus Data", @contact, method: :delete,class:'btn btn-danger btn-sm' %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BelajarRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Contacts Apps</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
          <%= link_to "Home", root_path,class: 'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to "Tambah Kontak", new_contact_path,class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>